name: 6ix4 Automate React Testing

on:
  pull_request:
    branches:
      - main

jobs:
  ReactTester:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 😉🚦
        uses: actions/checkout@v4.1.1

      - name: Use Node.js 18.x 🧑‍🔧
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18.x

      - name: Install Dependencies 🐞
        run: npm ci

      - name: Run Tests by vitest 🤖
        run: npm test