name: Hello I'm Flow

on:
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ☑️🚦
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}

      - name: just say hello ❤️❤️
        run: echo "No anything i want just say hello to you 😁😁😁"